2023-09-04 17:48:45 [Database Error] A database error occurred
Details: Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot
#0 C:\xampp\htdocs\rabitTrial\db.php(55): mysqli->__construct('localhost', 'root', Object(SensitiveParameterValue), 'rabittrial')
#1 C:\xampp\htdocs\rabitTrial\view\users.php(16): require_once('C:\\xampp\\htdocs...')
#2 {main}
2023-09-04 18:03:51 [Database Error] A database error occurred
Details: Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot
#0 C:\xampp\htdocs\rabitTrial\db.php(55): mysqli->__construct('localhost', 'root', Object(SensitiveParameterValue), 'rabittrial')
#1 C:\xampp\htdocs\rabitTrial\view\users.php(16): require_once('C:\\xampp\\htdocs...')
#2 {main}
2023-09-05 09:30:54 [Database Error] A database error occurred
Details: Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot
#0 C:\xampp\htdocs\rabitTrial\db.php(55): mysqli->__construct('localhost', 'root', Object(SensitiveParameterValue), 'rabittrial')
#1 C:\xampp\htdocs\rabitTrial\view\users.php(6): require_once('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\rabitTrial\index.php(41): include('C:\\xampp\\htdocs...')
#3 {main}
2023-09-05 09:33:00 [Database Error] A database error occurred
Details: Nem hozható létre kapcsolat, mert a célszámítógép már visszautasította a kapcsolatot
#0 C:\xampp\htdocs\rabitTrial\db.php(55): mysqli->__construct('localhost', 'root', Object(SensitiveParameterValue), 'rabittrial')
#1 C:\xampp\htdocs\rabitTrial\view\users.php(6): require_once('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\rabitTrial\index.php(41): include('C:\\xampp\\htdocs...')
#3 {main}
